# Generated by Django 5.2.2 on 2025-06-12 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario', 'Usuario')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_telefono', message='El teléfono debe tener exactamente 10 dígitos.', regex='^\\d{10}$')]),
        ),
    ]
