# Generated by Django 5.2.2 on 2025-06-13 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_usuario_rol_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_telefono', message='El teléfono debe tener exactamente 10 dígitos.', regex='^\\d{10}$')]),
        ),
    ]
