# Generated by Django 5.2.2 on 2025-06-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_categoria_created_at_categoria_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
